name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: joshcass/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: joshcass
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Los_Angeles
          base_indepth: yes
          config_display: large
          repositories_affiliations: owner, collaborator, organization_member
          repositories: 500
